# Generated by Django 5.1.3 on 2026-05-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_rename_date_expense_payment_date_expense_bill_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='payment_date',
            new_name='date',
        ),
    ]
